name: "FreeBSD"
on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'
  pull_request:
    paths-ignore:
      - 'docs/*'
      - '*.yml'
      - '*.md'
      - 'LICENSE'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:  
  freebsd:
    runs-on: macos-12
    strategy:
      matrix:
        os:
          - freebsd-latest
        version:
          - mini
    name: Build & Test
    steps:
      - name: "Cancel similar actions in progress"
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Setup environment & Build Arturo
        id: test
        uses: vmactions/freebsd-vm@v0
        with:
          usesh: true
          prepare: pkg install -y nim gmp mpfr bash databases/sqlite3
          run: |
            ./build.nims install ${{ matrix.version }} log
            export PATH="$HOME/.arturo/bin:$PATH"
            arturo tools/tester.art
       
      - name: Upload Artifacts
        uses: 'actions/upload-artifact@v2'
        with:
          name: "arturo-${{matrix.version}}-${{matrix.os}}"
          path: bin/arturo
